server:
  port: 80
spring:
  application.name: gateway-service

  cloud:
    gateway:
      routes:
        - id: resources
          uri: http://the-project:8085/client-service/test
          predicates:
            Path=/client-service/**

  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: my-provider
            client-id: client-id
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://the-project/login/oauth2/code/{registrationId}"
            scope: openid, message.read
        provider:
          my-provider:
            issuer-uri: http://auth-server:9900

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org:
      springframework:
        security: trace