version: '2.2'
services:
  elasticsearch:
    container_name: hexa-es
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    environment:
      - node.name=hexa-es
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_USERNAME=${ELASTIC_USERNAME}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}

    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ${ELASTIC_DATA_FILE}:/usr/share/elasticsearch/data
    ports:
      - 9300:9300
      - ${ELASTIC_PORT}:9200
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    container_name: hexa-kibana
    environment:
      ELASTICSEARCH_URL: http://hexa-es:${ELASTIC_PORT}
      ELASTICSEARCH_HOSTS: http://hexa-es:${ELASTIC_PORT}
      ELASTICSEARCH_USERNAME: ${ELASTIC_USERNAME}
      ELASTICSEARCH_USERNAME: ${ELASTIC_PASSWORD}
    ports:
      - 5601:5601
    volumes:
      - ${KIBANA_DATA_FILE}:/usr/share/kibana/data
    networks:
      - elastic

  logstash:
    image: docker.elastic.co/logstash/logstash:${STACK_VERSION}
    container_name: hexa-ls
    ports:
      - ${LOGSTASH_PORT}:5044
    networks:
      - elastic
    user: root
    volumes:
      - ${LOGSTASH_DIRECTORY}/certs:/usr/share/logstash/certs
      - ${LOGSTASH_DIRECTORY}/data:/usr/share/logstash/data
      - ${LOGSTASH_DIRECTORY}/ingest_data:/usr/share/logstash/ingest_data/
      - /Users/elmustafafriri/work/demos/SpringMonitoringAndTracing/docker/elk/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    environment:
      - xpack.monitoring.enabled=false
      - ELASTIC_USER=${ELASTIC_USERNAME}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ELASTIC_HOSTS=http://hexa-es:${ELASTIC_PORT}
      - LOGSTASH_PORT=${LOGSTASH_PORT}
networks:
  elastic:
    driver: bridge